networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    

  backend:
    build:
      context: ./Backend
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./Frontend
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cpu_shares: 512 